# Site settings
title: Coding Notes
email: timothyofficer@gmail.com
description: Coding notes
baseurl: "/personal_website" # the subpath of your site, e.g. /blog/
url: "http://codingnotes.com" # the base hostname & protocol for your site
twitter_username: timothyOfficer
github_username:  officert
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
